name: hatch_project
channels:
  - conda-forge
dependencies:
  - conda: adaptive-scheduler  # [linux64]
  - pip: unidep  # [linux64]
  - numpy >=1.21
  - hpc05  # [linux64]
  - pandas >=1,<3
  - pexpect # [unix]
  - wexpect # [win]
optional_dependencies:
  test:
    - pytest
    - pytest-cov
