name: company-pipelines
channels:
  - conda-forge
dependencies:
  - pipefunc
  - qiskit
local_dependencies:
  # Simple string format (backwards compatible)
  - ../dev-requirements.yaml

  # New dictionary format with PyPI alternative
  - local: ../foo
    pypi: company-foo

  - local: ../bar
    pypi: company-bar>=2.0.0

  # Can still use simple format for local-only dependencies
  - ../common-requirements.yaml

  # Dictionary format without PyPI alternative (same as string format)
  - local: ../third_party/foobar
    pypi: company-foobar~=1.0

# When building wheels (e.g., for distribution to a private PyPI):
# The PyPI alternatives will be used automatically
#
# For local development:
# The local paths will be used for editable installs
